### ISSUE TITLE
Gesamt-Statistiken/Spiele scheitert mit NPE für Turniere

### ISSUE THREAD

**Issue by huebener** [huebener/gameday-nrw#107]
Wurde durch #106 verdeckt, jetzt tritt eine NPE auf der zweiten Seite der Spiel Gesamtstatistik auf.
http://www.afsv-nrw.de/Gameday/Exec.do?command=Info&action=games

Stacktrace:
2-May-2016 21:26:54.501 SEVERE [http-nio-8080-exec-17] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
 java.lang.NullPointerException
	at huebener.gameday.ui.tags.foul.TeamFoulTag.getFouls(TeamFoulTag.java:48)
	at huebener.gameday.ui.tags.foul.QuarterFoulYardsTag.doStartTag(QuarterFoulYardsTag.java:31)
	at org.apache.jsp.WEB_002dINF.content.info.games_jsp._jspx_meth_gd_005fQuarterFoulYards_005f0(games_jsp.java:8142)
	at org.apache.jsp.WEB_002dINF.content.info.games_jsp._jspx_meth_gd_005fTeamFoul_005f0(games_jsp.java:8101)
	at org.apache.jsp.WEB_002dINF.content.info.games_jsp._jspx_meth_display_005fcolumn_005f13(games_jsp.java:8063)
	at org.apache.jsp.WEB_002dINF.content.info.games_jsp._jspService(games_jsp.java:788)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:403)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:347)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:301)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
	at huebener.gameday.controller.global.command.AbstractCommand.forward(AbstractCommand.java:116)
	at huebener.gameday.controller.global.action.info.GamesStatsAction.process(GamesStatsAction.java:29)
	at huebener.gameday.controller.global.command.AbstractCommand.process(AbstractCommand.java:69)
	at huebener.gameday.controller.global.command.AbstractCommand.process(AbstractCommand.java:58)
	at huebener.gameday.controller.global.FrontServlet.doGet(FrontServlet.java:40)

**Comment by huebener** [comment]
Root Cause: Es sind die Turnier (mal wieder), da sie keine Strafen und Scores haben.
